"use client";

import { useResearchStore } from "@/lib/store";
import { useRef, use } from "react";
import ReactMarkdown from "react-markdown";
import { useReactToPrint } from "react-to-print";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Printer, Download, FileText } from "lucide-react";

export default function ReportPage({
    params,
}: {
    params: Promise<{ id: string }>;
}) {
    const resolvedParams = use(params);
    const { draftReport, query } = useResearchStore();
    const printRef = useRef<HTMLDivElement>(null);
    const queryId = decodeURIComponent(resolvedParams.id);

    const handlePrint = useReactToPrint({
        contentRef: printRef,
        documentTitle: `Research_Report_${query || queryId}`,
    });

    const handleDownload = () => {
        if (!draftReport) {
            return;
        }
        const element = document.createElement("a");
        const file = new Blob([draftReport], { type: "text/markdown" });
        element.href = URL.createObjectURL(file);
        element.download = `Research_Report_${query || queryId}.md`;
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
        URL.revokeObjectURL(element.href);
    };

    return (
        <div className="space-y-6 animate-in fade-in">
            <div className="flex justify-between items-center">
                <div>
                    <h2 className="text-2xl font-bold tracking-tight">
                        Research Report
                    </h2>
                    <p className="text-muted-foreground">
                        Synthesized findings and strategic insights.
                    </p>
                </div>
                <div className="flex gap-2">
                    <Button
                        variant="outline"
                        size="sm"
                        onClick={handleDownload}
                        disabled={!draftReport}
                    >
                        <Download className="mr-2 h-4 w-4" /> Download MD
                    </Button>
                    <Button variant="default" size="sm" onClick={handlePrint}>
                        <Printer className="mr-2 h-4 w-4" /> Print / PDF
                    </Button>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
                <div className="hidden lg:block col-span-1">
                    <Card className="sticky top-24 p-4">
                        <h4 className="font-semibold mb-2 flex items-center gap-2">
                            <FileText className="h-4 w-4 text-primary" />{" "}
                            Contents
                        </h4>
                        <nav className="text-sm text-muted-foreground space-y-2">
                            <p>Executive Summary</p>
                            <p>Key Trends</p>
                            <p>Gap Analysis</p>
                            <p>References</p>
                        </nav>
                    </Card>
                </div>

                <div className="lg:col-span-3">
                    <Card className="p-8 min-h-[80vh] bg-background print:shadow-none print:border-none">
                        <div
                            ref={printRef}
                            className="prose prose-zinc dark:prose-invert max-w-none print:prose-black"
                        >
                            {draftReport ? (
                                <ReactMarkdown>{draftReport}</ReactMarkdown>
                            ) : (
                                <div className="text-center py-20 text-muted-foreground">
                                    Report generation pending. Please wait for
                                    the agent to complete the cycle.
                                </div>
                            )}
                            <div className="mt-12 pt-8 border-t text-xs text-center text-muted-foreground hidden print:block">
                                Generated by VRA Research Intelligence
                            </div>
                        </div>
                    </Card>
                </div>
            </div>
        </div>
    );
}
