# services/formatter/renderers/docx_renderer.py
from services.formatter.schema import FormattedReport, FormattedSection
from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
import io

class DocxRenderer:
    @staticmethod
    def render(report: FormattedReport) -> bytes:
        """
        Renders the report to DOCX and returns bytes.
        """
        doc = Document()
        
        # 1. Title
        doc.add_heading(report.title, 0)
        
        if report.subtitle:
            p = doc.add_paragraph(report.subtitle)
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            
        p = doc.add_paragraph()
        safe_date = report.date if report.date else "N/A"
        safe_authors = ", ".join(report.authors) if report.authors else "Unknown"
        p.add_run(f"Date: {safe_date}\n").bold = True
        p.add_run(f"Authors: {safe_authors}")
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER

        p2 = doc.add_paragraph()
        p2.add_run("Generated by AI Researcher - Automated Report").italic = True
        p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # 2. Table of Contents (Static)
        doc.add_page_break()
        doc.add_heading('Table of Contents', level=1)
        for section in report.sections:
             p = doc.add_paragraph()
             # numbering is like "1." or "1.1"
             prefix = f"{section.numbering} " if section.numbering else ""
             p.add_run(f"{prefix}{section.title}")
             # We cannot easily add page numbers in python-docx without complex XML hacking.
             # So we just list the sections.
        
        # 3. Abstract
        if report.abstract:
            doc.add_page_break()
            doc.add_heading('Abstract', level=1)
            doc.add_paragraph(report.abstract)
            
        # 4. Sections
        for section in report.sections:
            doc.add_page_break() # Start each main section on new page
            DocxRenderer._render_section(doc, section)
            
        # 5. References
        if report.references:
            doc.add_page_break()
            doc.add_heading('References', level=1)
            for ref in report.references:
                p = doc.add_paragraph()
                p.add_run(f"[{ref.index}] ").bold = True
                p.add_run(ref.text)
                if ref.url:
                    p.add_run(f" Available at: {ref.url}").italic = True

        # 6. Metadata Footer
        doc.add_page_break()
        import json
        meta_str = json.dumps(report.meta, ensure_ascii=False) if isinstance(report.meta, dict) else str(report.meta)
        p = doc.add_paragraph()
        p.add_run(f"Generated by AI Researcher - Metrics: {meta_str}").italic = True
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add Page Numbers to Footer
        # This requires accessing the section footer
        section = doc.sections[0]
        footer = section.footer
        p = footer.paragraphs[0]
        p.text = "Generated by AI Researcher \t" 
        # Adding actual page numbers is tricky in python-docx, usually requires XML insertion.
        # We will add a simple text for now.
        
        # Save to bytes
        file_stream = io.BytesIO()
        doc.save(file_stream)
        file_stream.seek(0)
        return file_stream.getvalue()

    @staticmethod
    def _render_section(doc, section: FormattedSection):
        # Heading
        # Ensure level is 1-9
        lvl = min(max(section.level, 1), 9)
        prefix = f"{section.numbering} " if section.numbering else ""
        doc.add_heading(f"{prefix}{section.title}", level=lvl)
        
        # Content - handle Markdown stripping? 
        # For now, simply dump text. Ideally we parse markdown to docx formatting.
        # Check if content has newlines
        if section.content:
            text = section.content # Fix: Do not strip markdown, keep as-is
            doc.add_paragraph(text)
            
        for sub in section.subsections or []:
            DocxRenderer._render_section(doc, sub)
