# services/formatter/renderers/markdown_renderer.py
from services.formatter.schema import FormattedReport, FormattedSection, FormattedReference
from typing import List

import json

class MarkdownRenderer:
    @staticmethod
    def render(report: FormattedReport) -> bytes:
        """
        Renders the report to Markdown and returns utf-8 bytes.
        """
        lines = []
        
        # 1. Title Block
        lines.append(f"# {report.title}")
        if report.subtitle:
            lines.append(f"**{report.subtitle}**")
        lines.append(f"**Date:** {report.date}  ")
        
        authors_text = ", ".join(report.authors) if report.authors else "Unknown"
        lines.append(f"**Authors:** {authors_text}")
        lines.append("\n --- \n")
        
        # 2. Abstract
        if report.abstract:
            lines.append("## Abstract")
            lines.append(report.abstract)
            lines.append("\n --- \n")
            
        # 3. Sections
        for section in report.sections:
            lines.extend(MarkdownRenderer._render_section(section))
            
        # 4. References
        if report.references:
            lines.append("\n## References")
            for ref in report.references:
                url_part = f" ([Link]({ref.url}))" if ref.url else ""
                lines.append(f"{ref.index}. {ref.text}{url_part}")
                
        # 5. Metadata Footer
        lines.append("\n---\n")
        
        meta_str = json.dumps(report.meta, ensure_ascii=False) if isinstance(report.meta, dict) else str(report.meta)
        lines.append(f"*Generated by AI Researcher - Metrics: {meta_str}*")
        
        return "\n".join(lines).encode('utf-8')

    @staticmethod
    def _render_section(section: FormattedSection) -> List[str]:
        lines = []
        # Calculate heading level (limit to 6)
        level_marker = "#" * max(1, min(section.level, 6))
        
        # Heading: "## 1. Introduction"
        prefix = f"{section.numbering} " if section.numbering else ""
        lines.append(f"{level_marker} {prefix}{section.title}")
        
        # Content
        if section.content:
            lines.append(section.content)
            
        lines.append("") # Spacing
        
        # Subsections
        for sub in section.subsections:
            lines.extend(MarkdownRenderer._render_section(sub))
            
        return lines
