# services/formatter/renderers/pdf_renderer.py
from services.formatter.schema import FormattedReport, FormattedSection
from fpdf import FPDF
import io
import logging

logger = logging.getLogger(__name__)

class PDF(FPDF):
    def __init__(self, authors, date):
        super().__init__()
        self.report_authors = authors
        self.report_date = date
        self.unicode_available = False
        
        # Try Loading Unicode Font (Windows)
        try:
            # Common Windows fonts
            font_path = "C:\\Windows\\Fonts\\arial.ttf"
            if os.path.exists(font_path):
                self.add_font("ArialUnicode", "", font_path, uni=True)
                self.add_font("ArialUnicode", "B", "C:\\Windows\\Fonts\\arialbd.ttf", uni=True)
                self.add_font("ArialUnicode", "I", "C:\\Windows\\Fonts\\ariali.ttf", uni=True)
                self.unicode_available = True
            else:
                # Try fallback or bundle? 
                # For now, we will rely on core fonts if custom font fails, 
                # but flag it so renderer knows to sanitize.
                pass
        except Exception as e:
            logger.warning(f"Failed to load Unicode font: {e}")

    def header(self):
        # Header Font
        family = 'ArialUnicode' if self.unicode_available else 'Arial'
        self.set_font(family, 'B', 15)
        # Move to the right
        # self.cell(80)
        # Title
        # self.cell(30, 10, 'Title', 1, 0, 'C')
        # Line break
        # self.ln(20)
        pass

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        family = 'ArialUnicode' if self.unicode_available else 'Arial'
        self.set_font(family, 'I', 8)
        # Page number
        self.cell(0, 10, 'Page ' + str(self.page_no()) + '/{nb}', 0, 0, 'C')

class PdfRenderer:
    @staticmethod
    def render(report: FormattedReport) -> bytes:
        """
        Renders PDF via FPDF2.
        """
        pdf = PDF(authors=", ".join(report.authors), date=report.date)
        pdf.alias_nb_pages()
        pdf.add_page()
        
        # 1. Title
        header_font = 'ArialUnicode' if pdf.unicode_available else 'Arial'
        
        pdf.set_font(header_font, 'B', 24)
        pdf.multi_cell(0, 10, report.title, align='C')
        pdf.ln(10)
        
        if report.subtitle:
            pdf.set_font(header_font, '', 16)
            pdf.multi_cell(0, 10, report.subtitle, align='C')
            pdf.ln(10)
            
        pdf.set_font(header_font, 'I', 10)
        pdf.cell(0, 10, f"Authors: {', '.join(report.authors)}", ln=True, align='C')
        pdf.cell(0, 10, f"Date: {report.date}", ln=True, align='C')
        pdf.ln(20)
        
        # 2. Abstract
        if report.abstract:
            pdf.set_font(header_font, 'B', 14)
            pdf.cell(0, 10, "Abstract", ln=True)
            pdf.set_font(header_font, '', 11)
            pdf.multi_cell(0, 5, report.abstract)
            pdf.ln(10)
            
        # 3. Sections
        for section in report.sections:
            PdfRenderer._render_section(pdf, section)
            
        # 4. References
        if report.references:
            pdf.add_page()
            pdf.set_font(header_font, 'B', 16)
            pdf.cell(0, 10, "References", ln=True)
            pdf.set_font(header_font, '', 10)
            for ref in report.references:
                text = f"[{ref.index}] {ref.text}"
                if ref.url:
                    text += f" ({ref.url})"
                pdf.multi_cell(0, 5, text)
                pdf.ln(2)

        # 5. Metadata Footer
        pdf.ln(10)
        footer_font = 'ArialUnicode' if pdf.unicode_available else 'Arial'
        pdf.set_font(footer_font, 'I', 8)
        import json
        meta_str = json.dumps(report.meta, ensure_ascii=False) if isinstance(report.meta, dict) else str(report.meta)
        pdf.multi_cell(0, 5, f"Generated by AI Researcher - Metrics: {meta_str}", align='C')

        # Output to bytes
        res = pdf.output()
        if isinstance(res, (bytes, bytearray)):
            return res
        elif isinstance(res, str):
            return res.encode('latin-1', 'replace')
        else:
            logger.error(f"Unexpected PDF output type: {type(res)}")
            return str(res).encode('utf-8', 'replace') 

    @staticmethod
    def _render_section(pdf: FPDF, section: FormattedSection):
        # Heading
        font_family = 'ArialUnicode' if pdf.unicode_available else 'Arial'
        pdf.set_font(font_family, 'B', 14 - min(section.level, 4))
        prefix = f"{section.numbering} " if section.numbering else ""
        pdf.cell(0, 10, f"{prefix}{section.title}", ln=True)
        
        # Content
        pdf.set_font(font_family, '', 11)
        if section.content:
            text = section.content
            
            if not pdf.unicode_available:
                # Fallback to Latin-1 sanitization
                try:
                    text = text.encode('latin-1')
                except UnicodeEncodeError as e:
                    logger.warning(f"PDF Encoding: Non-Latin-1 characters detected in section '{section.title}'. They will be replaced. content snippet: {section.content[e.start:e.end+10]!r}")
                    text = text.encode('latin-1', 'replace')
                text = text.decode('latin-1')
            
            # If unicode is available, FPDF2 handles utf-8 directly with TTF fonts
            pdf.multi_cell(0, 5, text)
        
        pdf.ln(5)
            
        for sub in section.subsections:
            PdfRenderer._render_section(pdf, sub)
