# services/formatter/renderers/pdf_renderer.py
from services.formatter.schema import FormattedReport, FormattedSection
from fpdf import FPDF
import io
import logging

logger = logging.getLogger(__name__)

class PDF(FPDF):
    def __init__(self, authors, date):
        super().__init__()
        self.report_authors = authors
        self.report_date = date
        self.unicode_available = False
        
        # Try Loading Unicode Font (Windows)
        try:
            # Common Windows fonts
            font_path = "C:\\Windows\\Fonts\\arial.ttf"
            if os.path.exists(font_path):
                self.add_font("ArialUnicode", "", font_path, uni=True)
                self.add_font("ArialUnicode", "B", "C:\\Windows\\Fonts\\arialbd.ttf", uni=True)
                self.add_font("ArialUnicode", "I", "C:\\Windows\\Fonts\\ariali.ttf", uni=True)
                self.unicode_available = True
            else:
                # Try fallback or bundle? 
                # For now, we will rely on core fonts if custom font fails, 
                # but flag it so renderer knows to sanitize.
                pass
        except Exception as e:
            logger.warning(f"Failed to load Unicode font: {e}")

    def header(self):
        # Header Font
        family = 'ArialUnicode' if self.unicode_available else 'Arial'
        self.set_font(family, 'B', 15)
        # Move to the right
        # self.cell(80)
        # Title
        # self.cell(30, 10, 'Title', 1, 0, 'C')
        # Line break
        # self.ln(20)
        pass

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        family = 'ArialUnicode' if self.unicode_available else 'Arial'
        self.set_font(family, 'I', 8)
        # Page number
        self.cell(0, 10, 'Page ' + str(self.page_no()) + '/{nb}', 0, 0, 'C')

class PdfRenderer:
    @staticmethod
    def render(report: FormattedReport) -> bytes:
        """
        Renders PDF via FPDF2.
        """
        pdf = PDF(authors=", ".join(report.authors), date=report.date)
        pdf.alias_nb_pages()
        pdf.add_page()
        
        # 1. Title
        header_font = 'ArialUnicode' if pdf.unicode_available else 'Arial'
        body_font = header_font # Use same font family for body, maybe different size/style
        
        pdf.set_font(header_font, 'B', 24)
        pdf.multi_cell(0, 10, report.title, align='C')
        pdf.ln(10)
        
        if report.subtitle:
            pdf.set_font(header_font, '', 16)
            pdf.multi_cell(0, 10, report.subtitle, align='C')
            pdf.ln(10)
            
        pdf.set_font(header_font, 'I', 10)
        pdf.cell(0, 5, f"Authors: {', '.join(report.authors)}", ln=True, align='C')
        pdf.cell(0, 5, f"Date: {report.date}", ln=True, align='C')
        pdf.ln(5)
        pdf.set_font(header_font, 'I', 8)
        pdf.cell(0, 5, "Generated by AI Researcher - Automated Report", ln=True, align='C')
        pdf.ln(20)
        
        # 2. Table of Contents
        pdf.insert_toc_placeholder(render_toc)
        
        # 3. Abstract
        if report.abstract:
            pdf.add_page()
            pdf.start_section("Abstract", level=1)
            pdf.set_font(header_font, 'B', 16)
            pdf.cell(0, 10, "Abstract", ln=True)
            pdf.set_font(body_font, '', 11)
            pdf.multi_cell(0, 6, report.abstract)
            
        # 4. Sections
        for section in report.sections:
            pdf.add_page() # Start main section on new page
            PdfRenderer._render_section(pdf, section, header_font, body_font)
            
        # 5. References
        if report.references:
            pdf.add_page()
            pdf.start_section("References", level=1)
            pdf.set_font(header_font, 'B', 16)
            pdf.cell(0, 10, "References", ln=True)
            pdf.set_font(body_font, '', 10)
            for ref in report.references:
                link = ref.url if ref.url else ""
                text = f"[{ref.index}] {ref.text}"
                pdf.multi_cell(0, 6, text, link=link)
                pdf.ln(2)

        # 6. Metadata Footer
        pdf.add_page()
        import json
        meta_str = json.dumps(report.meta, ensure_ascii=False) if isinstance(report.meta, dict) else str(report.meta)
        pdf.set_font('Courier', '', 8)
        pdf.set_text_color(100, 100, 100)
        pdf.multi_cell(0, 5, f"Metrics: {meta_str}")

        return bytes(pdf.output())

    @staticmethod
    def _render_section(pdf: FPDF, section: FormattedSection, header_font, body_font):
        # Heading
        # Ensure level is 1-6
        # FPDF2 start_section handles outline
        pdf.start_section(section.title, level=section.level)
        
        # Visually render heading
        sizes = {1: 16, 2: 14, 3: 12}
        size = sizes.get(section.level, 12)
        pdf.set_font(header_font, 'B', size)
        
        prefix = f"{section.numbering} " if section.numbering else ""
        pdf.cell(0, 10, f"{prefix}{section.title}", ln=True)
        
        # Content
        if section.content:
            pdf.set_font(body_font, '', 11)
            # Basic markdown stripping or rendering? 
            # For now, just dump text. 
            # Ideally we parse bold/italic.
            text = section.content
            
            if not pdf.unicode_available:
                # Fallback to Latin-1 sanitization
                try:
                    text = text.encode('latin-1')
                except UnicodeEncodeError as e:
                    logger.warning(f"PDF Encoding: Non-Latin-1 characters detected in section '{section.title}'. They will be replaced.")
                    text = text.encode('latin-1', 'replace')
                text = text.decode('latin-1')
            
            # If unicode is available, FPDF2 handles utf-8 directly with TTF fonts
            pdf.multi_cell(0, 5, text)
        
        pdf.ln(5)
            
        for sub in section.subsections:
            PdfRenderer._render_section(pdf, sub, header_font, body_font)


def render_toc(pdf, outline):
    # Check if outline is empty
    if not outline:
        return
        
    pdf.set_font("Helvetica", 'B', 16)
    pdf.cell(0, 10, "Table of Contents", ln=True)
    pdf.ln(5)
    pdf.set_font("Helvetica", '', 11)
    
    for section in outline:
        link = pdf.add_link()
        pdf.set_link(link, page=section.page_number)
        
        # Indent based on level
        indent = (section.level - 1) * 10
        pdf.set_x(pdf.l_margin + indent)
        
        # "Title ................... Page"
        # We use a simple cell for now
        text = f"{section.name}"
        pdf.cell(0, 5, text, link=link, ln=True)
